apiVersion: apps/v1
kind: Deployment
metadata:
  name: myclone-netflix-app
  labels:
    app: myclone-netflix-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myclone-netflix-app
  template:
    metadata:
      labels:
        app: myclone-netflix-app
    spec:
      containers:
      - name: myclone-netflix-app
        image: rukevweubio/mycryptobot-app:v2.0.2 
        imagePullPolicy: Always
        ports:
        - containerPort: 80
