apiVersion: v1
kind: Service
metadata:
  name: myclone-netflix-app-service
spec:
  type: NodePort
  selector:
    app: myclone-netflix-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
