
apiVersion: v1
kind: Service
metadata:
  name: mycryptobot
  namespace: canary-deploy
spec:
  type: NodePort
  selector:
    app: mycryptobot
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30082
